# Generated by Django 4.0.5 on 2022-06-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyects',
            new_name='Project',
        ),
    ]
